import Mathlib

open Complex Real MeasureTheory Filter
open scoped Topology

#check ContinuousLinearMap.integral
#check map_integral
#check integral_ofReal
#check Complex.ofRealCLM
#check Complex.ofRealLm
#check Complex.ofRealAm
#check Complex.ofReal_integral
#check MeasureTheory.integral_ofReal
#check intervalIntegral.integral_ofReal
#check Complex.ofReal_tsum
#check Complex.ofReal_log
#check Complex.ofReal_cpow
#check Complex.norm_cpow_eq_rpow_re_of_pos
#check Complex.continuousAt_cpow
#check HasDerivAt.cpow_const
#check HasDerivAt.const_cpow
#check HasDerivAt.const_mul
#check HasDerivAt.add_const
#check DifferentiableOn.analyticOnNhd
#check AnalyticAt.re_ofReal
#check AnalyticOnNhd.analyticAt
#check AnalyticAt.congr
#check AnalyticAt.const
#check AnalyticAt.id
#check AnalyticOnNhd.eqOn_of_preconnected_of_frequently_eq
#check eqOn_of_preconnected_of_eventuallyEq
#check isPreconnected_Ioi
#check convex_halfPlane
#check Convex.isPreconnected
#check Real.summable_nat_rpow
#check Real.summable_nat_add_one_rpow
#check Real.log_natCast_le_rpow_div
#check Summable.of_norm_bounded
#check hasDerivAt_tsum_of_isPreconnected
#check hasDerivAt_integral_of_dominated_loc_of_deriv_le
#check ContinuousOn.aestronglyMeasurable
#check intervalIntegrable_iff_integrableOn_Icc_of_le
#check ContinuousOn.integrableOn_Icc
#check norm_integral_le_integral_norm
#check intervalIntegral.norm_integral_le_integral_norm
#check intervalIntegral.integral_mono_on
#check intervalIntegral.integral_const_mul
#check intervalIntegral.integral_const
#check intervalIntegral.integral_id
#check intervalIntegral.integral_sub
#check intervalIntegral.intervalIntegrable_id
#check intervalIntegral.intervalIntegrable_const
#check intervalIntegral.intervalIntegrable_norm_iff
#check eventually_of_forall
#check frequently_of_mem
#check Filter.mem_of_superset
#check mem_nhdsWithin_iff_exists_mem_nhds_inter
#check continuousOn_of_forall_continuousAt
#check ContinuousOn.mono
#check Real.log_le_log
#check rpow_le_rpow_of_exponent_ge
#check rpow_add
#check mul_rpow
#check Complex.mem_slitPlane_iff
#check Complex.ofReal_log
#check analyticAt_const
#check analyticAt_id
#check AnalyticAt.mul
#check AnalyticAt.sub
#check Differentiable.analyticAt
#check measurableSet_uIoc
#check ae_of_all
#check Set.uIoc_of_le
#check Complex.continuousAt_log
#check continuousOfReal
#check continuous_ofReal
#check rpow_natCast
#check zeta_eq_tsum_one_div_nat_add_one_cpow
#check ZetaAsymptotics.zeta_limit_aux1
#check riemannZeta₀
#check differentiable_riemannZeta₀
#check Complex.ofReal_re
