import Mathlib

/-!
# Door 3 exact-rational candidate certificate table

This file is generated by `generate_door3_certificates.py`.  Its
arithmetic is kernel checked, but the table is not an analytic proof:
the ξ centre and derivative inequalities are intentionally separate
fields in `central_cover_assembly.lean` and are not asserted here.
-/

structure Door3RationalCandidate where
  index : Nat
  x0 : ℚ
  x1 : ℚ
  y0 : ℚ
  y1 : ℚ
  epsilon : ℚ
  derivUpper : ℚ
  centerLower : ℚ
deriving DecidableEq, Repr

def door3RationalCandidates : List Door3RationalCandidate := [
  { index := 0, x0 := -10, x1 := -7.5, y0 := 0.3, y1 := 0.49,
    epsilon := 0.007424384779909873517866608949, derivUpper := 0.051860382007074718256127039867, centerLower := 0.074243847799098735178666089497 },
  { index := 1, x0 := -10, x1 := -7.5, y0 := 0.2, y1 := 0.4,
    epsilon := 0.007404952292884223088975739550, derivUpper := 0.051707743327825077942127249806, centerLower := 0.074049522928842230889757395509 },
  { index := 2, x0 := -10, x1 := -7.5, y0 := 0.1, y1 := 0.3,
    epsilon := 0.007390256624686916288780644568, derivUpper := 0.051574638624003645518113274053, centerLower := 0.073902566246869162887806445686 },
  { index := 3, x0 := -10, x1 := -7.5, y0 := 0.01, y1 := 0.2,
    epsilon := 0.007381748495849003136902561488, derivUpper := 0.051479727682612327804816983733, centerLower := 0.073817484958490031369025614889 },
  { index := 4, x0 := -8, x1 := -5.5, y0 := 0.3, y1 := 0.49,
    epsilon := 0.016680679691851452278074404785, derivUpper := 0.068995437181212785699136703603, centerLower := 0.166806796918514522780744047850 },
  { index := 5, x0 := -8, x1 := -5.5, y0 := 0.2, y1 := 0.4,
    epsilon := 0.016647376496671398529854445367, derivUpper := 0.068770131691019824114868274595, centerLower := 0.166473764966713985298544453676 },
  { index := 6, x0 := -8, x1 := -5.5, y0 := 0.1, y1 := 0.3,
    epsilon := 0.016622191246658966572008345596, derivUpper := 0.068573619426536470084881775131, centerLower := 0.166221912466589665720083455961 },
  { index := 7, x0 := -8, x1 := -5.5, y0 := 0.01, y1 := 0.2,
    epsilon := 0.016607610141592806573788003361, derivUpper := 0.068433472341236467925198666748, centerLower := 0.166076101415928065737880033619 },
  { index := 8, x0 := -6, x1 := -3.5, y0 := 0.3, y1 := 0.49,
    epsilon := 0.029339777436442521059185822667, derivUpper := 0.070800657087089466893359570625, centerLower := 0.293397774364425210591858226675 },
  { index := 9, x0 := -6, x1 := -3.5, y0 := 0.2, y1 := 0.4,
    epsilon := 0.029289378002203542300809232337, derivUpper := 0.070542863192880039575409261754, centerLower := 0.292893780022035423008092323373 },
  { index := 10, x0 := -6, x1 := -3.5, y0 := 0.1, y1 := 0.3,
    epsilon := 0.029251261446053521447522094925, derivUpper := 0.070317966586413299239346056624, centerLower := 0.292512614460535214475220949253 },
  { index := 11, x0 := -6, x1 := -3.5, y0 := 0.01, y1 := 0.2,
    epsilon := 0.029229192752318905672763241636, derivUpper := 0.070157549106481366647352220453, centerLower := 0.292291927523189056727632416367 },
  { index := 12, x0 := -4, x1 := -1.5, y0 := 0.3, y1 := 0.49,
    epsilon := 0.041853473248929900347376698486, derivUpper := 0.069044953918578224868167673121, centerLower := 0.418534732489299003473766984862 },
  { index := 13, x0 := -4, x1 := -1.5, y0 := 0.2, y1 := 0.4,
    epsilon := 0.041787244504987704491024339733, derivUpper := 0.068748172749031776101105129590, centerLower := 0.417872445049877044910243397333 },
  { index := 14, x0 := -4, x1 := -1.5, y0 := 0.1, y1 := 0.3,
    epsilon := 0.041737153963777510202652947249, derivUpper := 0.068489153722532655651208743238, centerLower := 0.417371539637775102026529472491 },
  { index := 15, x0 := -4, x1 := -1.5, y0 := 0.01, y1 := 0.2,
    epsilon := 0.041708151617090899957208344207, derivUpper := 0.068304333393694676272150072042, centerLower := 0.417081516170908999572083442071 },
  { index := 16, x0 := -2, x1 := 0.5, y0 := 0.3, y1 := 0.49,
    epsilon := 0.049247558230693470183550754673, derivUpper := 0.045804998547154050548098490104, centerLower := 0.492475582306934701835507546731 },
  { index := 17, x0 := -2, x1 := 0.5, y0 := 0.2, y1 := 0.4,
    epsilon := 0.049172298768203854301584850042, derivUpper := 0.045291039725265234318071753899, centerLower := 0.491722987682038543015848500424 },
  { index := 18, x0 := -2, x1 := 0.5, y0 := 0.1, y1 := 0.3,
    epsilon := 0.049115376739988386140220002097, derivUpper := 0.044839807515496450298303750360, centerLower := 0.491153767399883861402200020974 },
  { index := 19, x0 := -2, x1 := 0.5, y0 := 0.01, y1 := 0.2,
    epsilon := 0.049082418453515397229614555100, derivUpper := 0.044516270332475767267252973905, centerLower := 0.490824184535153972296145551001 },
  { index := 20, x0 := 0, x1 := 2.5, y0 := 0.3, y1 := 0.49,
    epsilon := 0.048121677229997328752866052289, derivUpper := 0.053979227707703291608759169306, centerLower := 0.481216772299973287528660522896 },
  { index := 21, x0 := 0, x1 := 2.5, y0 := 0.2, y1 := 0.4,
    epsilon := 0.048047780216387685464327179704, derivUpper := 0.053550563645911998038642086545, centerLower := 0.480477802163876854643271797042 },
  { index := 22, x0 := 0, x1 := 2.5, y0 := 0.1, y1 := 0.3,
    epsilon := 0.047991888852435936910439814629, derivUpper := 0.053175333678552067989008678855, centerLower := 0.479918888524359369104398146295 },
  { index := 23, x0 := 0, x1 := 2.5, y0 := 0.01, y1 := 0.2,
    epsilon := 0.047959527401137992197938250571, derivUpper := 0.052906947524090887711005560836, centerLower := 0.479595274011379921979382505713 },
  { index := 24, x0 := 2, x1 := 4.5, y0 := 0.3, y1 := 0.49,
    epsilon := 0.039012049714083421820550351689, derivUpper := 0.070633307362675268453719133488, centerLower := 0.390120497140834218205503516895 },
  { index := 25, x0 := 2, x1 := 4.5, y0 := 0.2, y1 := 0.4,
    epsilon := 0.038949348265013617966700249633, derivUpper := 0.070363464903819074479795218212, centerLower := 0.389493482650136179667002496335 },
  { index := 26, x0 := 2, x1 := 4.5, y0 := 0.1, y1 := 0.3,
    epsilon := 0.038901925979422150457612818591, derivUpper := 0.070128031392791524272165410682, centerLower := 0.389019259794221504576128185919 },
  { index := 27, x0 := 2, x1 := 4.5, y0 := 0.01, y1 := 0.2,
    epsilon := 0.038874468733844750857892328725, derivUpper := 0.069960083125769948237402069813, centerLower := 0.388744687338447508578923287254 },
  { index := 28, x0 := 4, x1 := 6.5, y0 := 0.3, y1 := 0.49,
    epsilon := 0.026007116795952695746286663929, derivUpper := 0.070767818758717803531049657676, centerLower := 0.260071167959526957462866639299 },
  { index := 29, x0 := 4, x1 := 6.5, y0 := 0.2, y1 := 0.4,
    epsilon := 0.025961085573881603082295031126, derivUpper := 0.070513154991471335815899872596, centerLower := 0.259610855738816030822950311264 },
  { index := 30, x0 := 4, x1 := 6.5, y0 := 0.1, y1 := 0.3,
    epsilon := 0.025926273191359445815578178248, derivUpper := 0.070291627678290194201057195981, centerLower := 0.259262731913594458155781782485 },
  { index := 31, x0 := 4, x1 := 6.5, y0 := 0.01, y1 := 0.2,
    epsilon := 0.025906117758792817118265362241, derivUpper := 0.070133617482747617812956568627, centerLower := 0.259061177587928171182653622416 },
  { index := 32, x0 := 6, x1 := 8.5, y0 := 0.3, y1 := 0.49,
    epsilon := 0.013969125294017149220259011834, derivUpper := 0.066100758566877127751364854937, centerLower := 0.139691252940171492202590118340 },
  { index := 33, x0 := 6, x1 := 8.5, y0 := 0.2, y1 := 0.4,
    epsilon := 0.013939713115663644403479332030, derivUpper := 0.065895075425236776834317677333, centerLower := 0.139397131156636444034793320304 },
  { index := 34, x0 := 6, x1 := 8.5, y0 := 0.1, y1 := 0.3,
    epsilon := 0.013917470697206126226175582990, derivUpper := 0.065715692538335737393469675905, centerLower := 0.139174706972061262261755829907 },
  { index := 35, x0 := 6, x1 := 8.5, y0 := 0.01, y1 := 0.2,
    epsilon := 0.013904593468320804151235150174, derivUpper := 0.065587770072798720399051771962, centerLower := 0.139045934683208041512351501741 },
  { index := 36, x0 := 7.5, x1 := 10, y0 := 0.3, y1 := 0.49,
    epsilon := 0.007424384779909873517866608949, derivUpper := 0.051860382007074718256127039867, centerLower := 0.074243847799098735178666089497 },
  { index := 37, x0 := 7.5, x1 := 10, y0 := 0.2, y1 := 0.4,
    epsilon := 0.007404952292884223088975739550, derivUpper := 0.051707743327825077942127249806, centerLower := 0.074049522928842230889757395509 },
  { index := 38, x0 := 7.5, x1 := 10, y0 := 0.1, y1 := 0.3,
    epsilon := 0.007390256624686916288780644568, derivUpper := 0.051574638624003645518113274053, centerLower := 0.073902566246869162887806445686 },
  { index := 39, x0 := 7.5, x1 := 10, y0 := 0.01, y1 := 0.2,
    epsilon := 0.007381748495849003136902561488, derivUpper := 0.051479727682612327804816983733, centerLower := 0.073817484958490031369025614889 },
]

def Door3RationalCandidate.geometryOK (c : Door3RationalCandidate) : Prop :=
  ((c.x1 - c.x0) / 2)^2 + ((c.y1 - c.y0) / 2)^2 < (126 / 100 : ℚ)^2

def Door3RationalCandidate.arithmeticOK (c : Door3RationalCandidate) : Prop :=
  c.x0 < c.x1 ∧ c.y0 < c.y1 ∧ 0 < c.epsilon ∧ 0 ≤ c.derivUpper ∧
  c.epsilon + c.derivUpper * (126 / 100 : ℚ) ≤ c.centerLower ∧
  0 < c.centerLower - (c.epsilon + c.derivUpper * (126 / 100 : ℚ))

theorem door3_rational_candidates_nonempty : door3RationalCandidates ≠ [] := by
  intro h
  cases h

def door3CandidateOK (c : Door3RationalCandidate) : Bool :=
  decide (
    (((c.x1 - c.x0) / 2)^2 + ((c.y1 - c.y0) / 2)^2 < (126 / 100 : ℚ)^2) ∧
    c.x0 < c.x1 ∧ c.y0 < c.y1 ∧ 0 < c.epsilon ∧ 0 ≤ c.derivUpper ∧
    c.epsilon + c.derivUpper * (126 / 100 : ℚ) ≤ c.centerLower ∧
    0 < c.centerLower - (c.epsilon + c.derivUpper * (126 / 100 : ℚ)))

def door3ArithmeticAudit : Bool :=
  door3RationalCandidates.all door3CandidateOK

theorem door3_rational_candidates_arithmetic :
    door3ArithmeticAudit = true := by
  norm_num [door3ArithmeticAudit, door3CandidateOK, door3RationalCandidates]

#print axioms door3_rational_candidates_arithmetic
