"""Generate exact-rational Door-3 candidate certificates.

The input rows are high-precision sampled values.  This generator rounds the
centre lower bound and epsilon down and the derivative bound up, so every
arithmetic inequality is preserved by construction.  The resulting files
are *candidate* certificates: the numerical rows do not prove the analytic
claims about ``xiShifted`` or its derivative.  Those claims are recorded as
the separate obligations used by ``central_cover_assembly.lean``.
"""

from __future__ import annotations

import json
from decimal import Decimal, ROUND_CEILING, ROUND_FLOOR, getcontext
from pathlib import Path

getcontext().prec = 120
ROOT = Path(__file__).resolve().parent
SCALE_DIGITS = 30
SCALE = Decimal(10) ** SCALE_DIGITS


def outward(value: str, direction: str) -> str:
    x = Decimal(value) * SCALE
    mode = ROUND_FLOOR if direction == "down" else ROUND_CEILING
    n = x.to_integral_value(rounding=mode)
    y = n / SCALE
    # Fixed-point text is accepted by Lean's exact decimal elaborator and is
    # also unambiguous to downstream JSON/Fraction readers.
    return format(y, f".{SCALE_DIGITS}f")


def rational_rows() -> list[dict[str, object]]:
    source = json.loads((ROOT / "door3_numeric_targets.json").read_text())
    rows: list[dict[str, object]] = []
    for row in source["rows"]:
        out = {
            "index": row["index"],
            "x0": row["x0"],
            "x1": row["x1"],
            "y0": row["y0"],
            "y1": row["y1"],
            "center_lower": outward(row["center_norm"], "down"),
            "deriv_upper": outward(row["target_M"], "up"),
            "epsilon": outward(row["target_epsilon"], "down"),
            "sampled_center_norm": row["center_norm"],
            "sampled_deriv_max": row["mesh_deriv_max"],
            "sampled_margin": row["sampled_margin"],
            "samples": row["samples"],
        }
        c = Decimal(out["center_lower"])
        m = Decimal(out["deriv_upper"])
        e = Decimal(out["epsilon"])
        # The exact-rational shell uses the repository's certified geometric
        # radius cap 1.26, rather than the sampled floating-point radius.
        out["budget_margin"] = format(c - e - m * Decimal("1.26"), "f")
        if c - e - m * Decimal("1.26") <= 0:
            raise ValueError(f"row {row['index']} has no arithmetic margin")
        rows.append(out)
    return rows


def write_json(rows: list[dict[str, object]]) -> None:
    payload = {
        "schema": "door3-rational-candidate-v1",
        "status": "sampled_unverified",
        "source": "door3_numeric_targets.json",
        "rounding": {
            "center_lower": "floor to 30 decimal places",
            "deriv_upper": "ceil to 30 decimal places",
            "epsilon": "floor to 30 decimal places",
        },
        "geometric_radius_cap": "1.26",
        "analytic_obligations": [
            "epsilon + deriv_upper * radius <= ||xiShifted center||",
            "forall z in rectangle, ||deriv xiShifted z|| <= deriv_upper",
        ],
        "rows": rows,
    }
    (ROOT / "door3_rational_certificates.json").write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8"
    )


def lean_num(value: str) -> str:
    # Lean parses fixed-point decimal numerals as exact rationals when the
    # expected type is ℚ.
    return value


def write_lean(rows: list[dict[str, object]]) -> None:
    lines = [
        "import Mathlib",
        "",
        "/-!",
        "# Door 3 exact-rational candidate certificate table",
        "",
        "This file is generated by `generate_door3_certificates.py`.  Its",
        "arithmetic is kernel checked, but the table is not an analytic proof:",
        "the ξ centre and derivative inequalities are intentionally separate",
        "fields in `central_cover_assembly.lean` and are not asserted here.",
        "-/",
        "",
        "structure Door3RationalCandidate where",
        "  index : Nat",
        "  x0 : ℚ",
        "  x1 : ℚ",
        "  y0 : ℚ",
        "  y1 : ℚ",
        "  epsilon : ℚ",
        "  derivUpper : ℚ",
        "  centerLower : ℚ",
        "deriving DecidableEq, Repr",
        "",
        "def door3RationalCandidates : List Door3RationalCandidate := [",
    ]
    for r in rows:
        lines.append(
            "  { index := %s, x0 := %s, x1 := %s, y0 := %s, y1 := %s,"
            % (r["index"], lean_num(r["x0"]), lean_num(r["x1"]), lean_num(r["y0"]), lean_num(r["y1"])),
        )
        lines.append(
            "    epsilon := %s, derivUpper := %s, centerLower := %s },"
            % (lean_num(r["epsilon"]), lean_num(r["deriv_upper"]), lean_num(r["center_lower"])),
        )
    lines += [
        "]",
        "",
        "def Door3RationalCandidate.geometryOK (c : Door3RationalCandidate) : Prop :=",
        "  ((c.x1 - c.x0) / 2)^2 + ((c.y1 - c.y0) / 2)^2 < (126 / 100 : ℚ)^2",
        "",
        "def Door3RationalCandidate.arithmeticOK (c : Door3RationalCandidate) : Prop :=",
        "  c.x0 < c.x1 ∧ c.y0 < c.y1 ∧ 0 < c.epsilon ∧ 0 ≤ c.derivUpper ∧",
        "  c.epsilon + c.derivUpper * (126 / 100 : ℚ) ≤ c.centerLower ∧",
        "  0 < c.centerLower - (c.epsilon + c.derivUpper * (126 / 100 : ℚ))",
        "",
        "theorem door3_rational_candidates_nonempty : door3RationalCandidates ≠ [] := by",
        "  intro h",
        "  cases h",
        "",
        "def door3CandidateOK (c : Door3RationalCandidate) : Bool :=",
        "  decide (",
        "    (((c.x1 - c.x0) / 2)^2 + ((c.y1 - c.y0) / 2)^2 < (126 / 100 : ℚ)^2) ∧",
        "    c.x0 < c.x1 ∧ c.y0 < c.y1 ∧ 0 < c.epsilon ∧ 0 ≤ c.derivUpper ∧",
        "    c.epsilon + c.derivUpper * (126 / 100 : ℚ) ≤ c.centerLower ∧",
        "    0 < c.centerLower - (c.epsilon + c.derivUpper * (126 / 100 : ℚ)))",
        "",
        "def door3ArithmeticAudit : Bool :=",
        "  door3RationalCandidates.all door3CandidateOK",
        "",
        "theorem door3_rational_candidates_arithmetic :",
        "    door3ArithmeticAudit = true := by",
        "  norm_num [door3ArithmeticAudit, door3CandidateOK, door3RationalCandidates]",
        "",
        "#print axioms door3_rational_candidates_arithmetic",
        "",
    ]
    (ROOT / "door3_rational_certificates.lean").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    rows = rational_rows()
    write_json(rows)
    write_lean(rows)
    print(f"generated {len(rows)} exact-rational candidate rows")
