import Mathlib

open Complex Real

noncomputable section

/-!
# Central region certificate data -- 32 cells covering Re z in [-10,10], Im z in [0.01, 0.49]

Generated by gen_central_cover_data.py using mpmath (50 dps).
Each cell: lower bound on |xi| at center, derivative bound M, and eps such that
eps + M*radius <= |xi(center)| (Taylor fencing condition, verified positive).

FLOAT DATA -- precomputed Float lower bounds, verified consistent by `decide`.
Connection to actual xi nonvanishing requires a computable xi approximation.
-/

structure CentralCell where
  x0 : Float
  x1 : Float
  y0 : Float
  y1 : Float
  eps : Float
  M : Float

deriving instance Inhabited for CentralCell

def central_cert_data : Array CentralCell := #[
  CentralCell.mk (-10.0:Float) (-7.5:Float) (0.01:Float) (0.2:Float) (0.006177051945015177:Float) (0.04902931207867841:Float),
  CentralCell.mk (-7.5:Float) (-5.0:Float) (0.01:Float) (0.2:Float) (0.0559279239515775:Float) (0.06662501762533198:Float),
  CentralCell.mk (-5.0:Float) (-2.5:Float) (0.01:Float) (0.2:Float) (0.13714195825263417:Float) (0.06673567631500821:Float),
  CentralCell.mk (-2.5:Float) (0.0:Float) (0.01:Float) (0.2:Float) (0.20821396092526187:Float) (0.05038856907056275:Float),
  CentralCell.mk (0.0:Float) (2.5:Float) (0.01:Float) (0.2:Float) (0.20821396092526187:Float) (0.05038856907056275:Float),
  CentralCell.mk (2.5:Float) (5.0:Float) (0.01:Float) (0.2:Float) (0.13714195825263417:Float) (0.06673567631500821:Float),
  CentralCell.mk (5.0:Float) (7.5:Float) (0.01:Float) (0.2:Float) (0.0559279239515775:Float) (0.06662501762533198:Float),
  CentralCell.mk (7.5:Float) (10.0:Float) (0.01:Float) (0.2:Float) (0.006177051945015177:Float) (0.04902931207867841:Float),
  CentralCell.mk (-10.0:Float) (-7.5:Float) (0.2:Float) (0.3:Float) (0.006259972847889726:Float) (0.049119703451432045:Float),
  CentralCell.mk (-7.5:Float) (-5.0:Float) (0.2:Float) (0.3:Float) (0.056068903077646316:Float) (0.06677104484106818:Float),
  CentralCell.mk (-5.0:Float) (-2.5:Float) (0.2:Float) (0.3:Float) (0.13735924009344982:Float) (0.0668931834879488:Float),
  CentralCell.mk (-2.5:Float) (0.0:Float) (0.2:Float) (0.3:Float) (0.20840724121203882:Float) (0.050644174931954354:Float),
  CentralCell.mk (0.0:Float) (2.5:Float) (0.2:Float) (0.3:Float) (0.20840724121203882:Float) (0.050644174931954354:Float),
  CentralCell.mk (2.5:Float) (5.0:Float) (0.2:Float) (0.3:Float) (0.13735924009344982:Float) (0.0668931834879488:Float),
  CentralCell.mk (5.0:Float) (7.5:Float) (0.2:Float) (0.3:Float) (0.056068903077646316:Float) (0.06677104484106818:Float),
  CentralCell.mk (7.5:Float) (10.0:Float) (0.2:Float) (0.3:Float) (0.006259972847889726:Float) (0.049119703451432045:Float),
  CentralCell.mk (-10.0:Float) (-7.5:Float) (0.3:Float) (0.4:Float) (0.006268912330277428:Float) (0.04924646983602388:Float),
  CentralCell.mk (-7.5:Float) (-5.0:Float) (0.3:Float) (0.4:Float) (0.05611069935418023:Float) (0.06697578146188994:Float),
  CentralCell.mk (-5.0:Float) (-2.5:Float) (0.3:Float) (0.4:Float) (0.1374882361414519:Float) (0.06711398748062603:Float),
  CentralCell.mk (-2.5:Float) (0.0:Float) (0.3:Float) (0.4:Float) (0.2085192587199296:Float) (0.05100153680563047:Float),
  CentralCell.mk (0.0:Float) (2.5:Float) (0.3:Float) (0.4:Float) (0.2085192587199296:Float) (0.05100153680563047:Float),
  CentralCell.mk (2.5:Float) (5.0:Float) (0.3:Float) (0.4:Float) (0.1374882361414519:Float) (0.06711398748062603:Float),
  CentralCell.mk (5.0:Float) (7.5:Float) (0.3:Float) (0.4:Float) (0.05611069935418023:Float) (0.06697578146188994:Float),
  CentralCell.mk (7.5:Float) (10.0:Float) (0.3:Float) (0.4:Float) (0.006268912330277428:Float) (0.04924646983602388:Float),
  CentralCell.mk (-10.0:Float) (-7.5:Float) (0.4:Float) (0.49:Float) (0.006293913564448431:Float) (0.049391840006737825:Float),
  CentralCell.mk (-7.5:Float) (-5.0:Float) (0.4:Float) (0.49:Float) (0.0561844236887777:Float) (0.067210486893171:Float),
  CentralCell.mk (-5.0:Float) (-2.5:Float) (0.4:Float) (0.49:Float) (0.1376730585040693:Float) (0.06736707229531062:Float),
  CentralCell.mk (-2.5:Float) (0.0:Float) (0.4:Float) (0.49:Float) (0.2086917661937123:Float) (0.051409788293050755:Float),
  CentralCell.mk (0.0:Float) (2.5:Float) (0.4:Float) (0.49:Float) (0.2086917661937123:Float) (0.051409788293050755:Float),
  CentralCell.mk (2.5:Float) (5.0:Float) (0.4:Float) (0.49:Float) (0.1376730585040693:Float) (0.06736707229531062:Float),
  CentralCell.mk (5.0:Float) (7.5:Float) (0.4:Float) (0.49:Float) (0.0561844236887777:Float) (0.067210486893171:Float),
  CentralCell.mk (7.5:Float) (10.0:Float) (0.4:Float) (0.49:Float) (0.006293913564448431:Float) (0.049391840006737825:Float)
]

set_option maxRecDepth 1000000

/-- All eps bounds are positive (verified by mpmath). -/
theorem central_cert_eps_pos : ∀ t ∈ central_cert_data, 0 < t.eps := by
  decide

/-- All M bounds are non-negative. -/
theorem central_cert_M_nonneg : ∀ t ∈ central_cert_data, 0 <= t.M := by decide
